### PR TITLE
Add websocket port to i18n and formatting

### PR DESCRIPTION
**Pull request by mattreim**
I changed also a few things in WEBLATE.

### CODE REVIEW

**Comment by mattreim** [comment]
Now I'm done. Please take a look.

**Comment by Jey-Cee** [comment]
I forget that deconz is checked in to the ioBroker weblate. If we have to change a translation we have to do it there as not this will cause problems.
Like here, what i can not fix by myself:
grafik

Weblate: https://weblate.iobroker.net/projects/adapters/
If you want to go deeper in adapter development i can recommend you to have a look into our development portal: https://www.iobroker.dev/

**Comment by mattreim** [comment]
However, the translations must first be present in the data. They will then be transferred to WEBLATE. I already had this discussion at “iobroker.ping”.

For clarification, websocket port does not exist yet.

**Comment by mattreim** [comment]
The changes in WEBLATE are only from the current Phoscon app and are intended to avoid confusion.

**Pull request merged**
