### PR TITLE
Update JSON [panel and divider]

### PR DESCRIPTION
**Pull request by mattreim**
json

1. Panel -> tab is now unnecessary
2. Divider and header -> for better readability

### CODE REVIEW

**Comment by Jey-Cee** [comment]
I am not happy with the second header. Yes it looks better, but header means new section which it isn't.

There is a technical reason why we should not do this in this way:
There are tools like screen reader they use this information for proper function.

The other reason is the EEA (European accessibility act) which says any digital interface has to be accessible for humans with disabilities and older ones. That means tools like screen readers must be able to read/interpret the interface.
Actual it is unclear if this has an impact on projects like ioBroker, but i think it is better to build our interface in a way that makes it also accessible for those people who have limitations and uses these tools.

**Comment by mattreim** [comment]
Less is more...

JSON

**Comment by Jey-Cee** [comment]
What do you think about this?
grafik
grafik

**Comment by mattreim** [comment]
I think it's good except for the tab ;)

**Comment by mattreim** [comment]
I think these things are better too.

Port -> min ->1
Websocket Port -> min ->1
_header1 -> "newLine": true, (just to be safe)

And I removed this sentence in WEBLATE because it is no longer a pop-up.

 "Instruction": ...Leave this message open.

**Comment by mattreim** [comment]
I think the innovations are very good.

**Comment by Jey-Cee** [comment]
I have applied the changes and released 1.6.1

**Pull request closed without merging**
