### PR TITLE
Change to Math.round and colormode unwritable

### PR DESCRIPTION
**Pull request by mattreim**

### CODE REVIEW

**Comment by mattreim** [comment]
Group

**Comment by mattreim** [comment]
I think it's just too dangerous for most users to change the switch groups on the adapter. That's why I deleted them again.

**Comment by mattreim** [comment]
During testing, I noticed that the objects in groups were not updated.

```lua
"action": {
       "bri": 0,
       "ct": 500,
       "effect": "none",
       "hue": 0,
       "on": false,
       "sat": 0,
       "xy": [ 0, 0 ]
}
```
state works
```lua
"state": {
       "all_on": false,
       "any_on": false
}
```

**Comment by Jey-Cee** [comment]
> During testing, I noticed that the objects in products were not updated.
> 
> ```lua
> "action": {
>        "bri": 0,
>        "ct": 500,
>        "effect": "none",
>        "hue": 0,
>        "on": false,
>        "sat": 0,
>        "xy": [ 0, 0 ]
> }
> ```
> 
> state works
> 
> ```lua
> "state": {
>        "all_on": false,
>        "any_on": false
> }
> ```

What do you mean with products?

**Comment by mattreim** [comment]
Sorry, of course I meant groups.

**Comment by Jey-Cee** [comment]
Yes i know that. The api does not deliver the changes on a group.

**Comment by mattreim** [comment]
I hadn't really noticed it yet.

**Pull request merged**
