### PR TITLE
Objects for plug and configuration tool reduced

### PR DESCRIPTION
**Pull request by mattreim**
Configuration tool:
Config
On/Off plug-in unit:
Plug
On/Off light:
on_off

The objects are unusable for these devices and therefore unnecessary.

```
action
dimup
dimdown
dimspeed
level
transitiontime 
```

### CODE REVIEW

**Comment by mattreim** [comment]
I was able to test these too.

**Comment by mattreim** [comment]
Phoscon lumi switch

lumi_switch

lumi_switch2

**Comment by mattreim** [comment]
@Jey-Cee What do you say about this PR?

**Comment by Jey-Cee** [comment]
I think its ok.

**Pull request merged**
