### PR TITLE
Basic framework for JSON Config [partially functional]

### PR DESCRIPTION
**Pull request by mattreim**
It is based on the current UI and is unfortunately not functional. Unfortunately I can't get any further.

iob-deConz

### CODE REVIEW

**Comment by Jey-Cee** [comment]
Looks good. Which part or parts are not functional?

**Comment by mattreim** [comment]
It doesn't seem to address the parameters in general. Only the translations work now.

**Comment by Jey-Cee** [comment]
I have released new version with JSONConfig, but removed the device and group management. This is bit more work to make it functional. 
I've made a survey and it seems that less than 25% of the user are using it. So i decided to not do this extra work for now.
But i leave this PR open for the future.

**Comment by mattreim** [comment]
It works very well and should also resolve issue #358, among other things. Thank you

**Pull request closed without merging**
