### PR TITLE
Hide virtual sensors and switch groups

### PR DESCRIPTION
**Pull request by mattreim**
deconz

### CODE REVIEW

**Comment by mattreim** [comment]
@Jey-Cee I think they are useful functions.

**Comment by mattreim** [comment]
The groups are working quite well so far but the CLIP sensors are created again when used.

**Comment by mattreim** [comment]
It now works well even overnight and with repeated targeted control.

**Comment by mattreim** [comment]
@Jey-Cee What do you think about this PR?

**Comment by Jey-Cee** [comment]
Yes it is a good idea. I am missing the native entries for the new settings in io-package.josn. Then we have a defined default value for this setting, these has to be false as this could cause unexpected behaviour on existing installations.

**Comment by mattreim** [comment]
It's done

**Comment by mattreim** [comment]
I still have two little things.

Do group states really have a transitiontime? I thought it only existed with action.
https://github.com/Jey-Cee/ioBroker.deconz/blob/1428d0b5375dcb2a738acf1aa4509e32706e5f77/main.js#L1131-L1138


And actually the same thing only with window covering (roller blind).
https://github.com/Jey-Cee/ioBroker.deconz/blob/1428d0b5375dcb2a738acf1aa4509e32706e5f77/main.js#L1988-L1994

**Comment by mattreim** [comment]
I just thought of one and according to the [documentation ](https://dresden-elektronik.github.io/deconz-rest-doc/endpoints/lights/#parameters_2)it is not supported by on either.

**Pull request merged**
