### PR TITLE
Re-enable Window covers

### PR DESCRIPTION
**Pull request by Grizzelbee**

### CODE REVIEW

**Comment by Grizzelbee** [comment]
Stupid question: Are there any plans to bring this version to stable or will it remain as a github only version?
Just to know how I need to update my stable environment.   ;o)

**Comment by Jey-Cee** [comment]
Yes after it was tested by users for 2 or 3 weeks and there are no problems with it

**Comment by Grizzelbee** [comment]
Okay. Fine for me. That's the usual way.
One more thing:  May you  please create the npm package for this version - I have no permissions to do that.

**Comment by Jey-Cee** [comment]
already done

**Pull request merged**
