### PR TITLE
Optimization

### PR DESCRIPTION
**Pull request by mattreim**
@Jey-Cee Also fixes code:400 warning when creating dimspeed and the jump from bri to 1 when selecting dimup/dimdown before the device is on.

### CODE REVIEW

**Comment by mattreim** [comment]
@Jey-Cee Now I've tried a few things again with a fresh installation and only have this one-time warning. What do you think of it?

`warn | State "deconz.0.Sensors.5.buttonpressed" has no existing object, this might lead to an error in future versions`

**Comment by Jey-Cee** [comment]
Without any context it isnt easy to say anything about this message.

**Comment by mattreim** [comment]
This message always appears the first time a switch is pressed and then no longer appears. But actually I meant the PR.

**Comment by mattreim** [comment]
I always test the changes with a new installation to detect errors early.

**Comment by mattreim** [comment]
Changes:
- Removing transitiontime from on and stop (boolean)
- Add default to dimspeed (Fix code:400 warning when creating dimspeed)
- Add , "on": true to dimup/dimdown (Fix the jump from bri to 1 when selecting dimup/dimdown before the device is on)
- Add transitiontime min even 0
- Remove transitiontime from group list["state"] and blind
- Formatting

**Comment by Jey-Cee** [comment]
Transition time is available on groups, so there is no reason to remove it. -> https://dresden-elektronik.github.io/deconz-rest-doc/endpoints/groups/#set-group-state

**Comment by mattreim** [comment]
I didn't delete it from action but from state.

list["action"]
https://github.com/Jey-Cee/ioBroker.deconz/blob/42c781facacc3e786967312943e6612d56fafb03/main.js#L995-L1003

list["state"]:
https://github.com/Jey-Cee/ioBroker.deconz/blob/42c781facacc3e786967312943e6612d56fafb03/main.js#L1004-L1009

So it still works.

**Comment by mattreim** [comment]
The list["state"] are two boolean in groups or not? Can be seen in the picture.

- all_on
- any_on

Group

**Comment by Jey-Cee** [comment]
> State are two boolean in groups or not?

Sorry i dont understand the question.

**Comment by mattreim** [comment]
I hope it's more understandable now.

**Comment by Jey-Cee** [comment]
Yes, they are two booleans.

**Comment by mattreim** [comment]
> Transition time is available on groups, so there is no reason to remove it.

That was the basic question and no, these two booleans have no transition time.

**Comment by mattreim** [comment]
But otherwise the PR is ok or should I change something else?

**Comment by Jey-Cee** [comment]
no its ok. Please update version and write the changelog, then we can release a beta for testing.

**Comment by mattreim** [comment]
It's done

**Pull request merged**
